=== NetsanetGeb/XML-Processing-and-Parsing/xml/TranscriptSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.Transcript.se" elementFormDefault="qualified">

	<xsd:element name="Transcript">
		<xsd:complexType>
			<xsd:sequence>

				<xsd:element name="Name" type="xsd:string" />

				<xsd:element name="PersonNumber">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="\d{6}-\d{4}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>

				<xsd:element name="University" type="xsd:string" />

				<xsd:element name="Degree" type="xsd:string" />

				<xsd:element name="Year">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="\d{4}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>

				<xsd:element name="Courses">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="Course" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:element name="Name" type="xsd:string" />

										<xsd:element name="Code">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="[B-K]{2}\d{4}" />
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>

										<xsd:element name="Grade">
											<xsd:simpleType>
												<xsd:restriction base="xsd:integer">
													<xsd:minInclusive value="1" />
													<xsd:maxInclusive value="4" />
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== NetsanetGeb/XML-Processing-and-Parsing/src/xmlprocessing/xmlDoc/TranscriptXMLDoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<t:Transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:t='http://www.Transcript.se'
    xsi:schemaLocation='http://www.Transcript.se ../xsd/TranscriptSchema.xsd'>
        <t:Name>Netsanet Gebretsadkan</t:Name>
	<t:PersonNumber>940823-0580</t:PersonNumber>
	<t:University>KTH</t:University>
	<t:Degree>MSc in Software Engineering of Distributed Systems</t:Degree>
	<t:Year>2018</t:Year>
	<t:Courses>
		<t:Course>
                        <t:Name> Distributed Systems, Basic Course </t:Name>
                        <t:Code> ID2201 </t:Code>
                        <t:Grade>4</t:Grade>
                </t:Course>
                <t:Course>
                         <t:Name> Modern Methods in Software Engineering </t:Name>
                        <t:Code> ID2207 </t:Code>
                        <t:Grade>3</t:Grade>  
                </t:Course>
                <t:Course>
                         <t:Name> Network Programming </t:Name>
                        <t:Code> ID1212 </t:Code>
                        <t:Grade>3</t:Grade>  
                </t:Course>
                <t:Course>
                        <t:Name> Distributed Artificial Intelligence </t:Name>
                        <t:Code> ID2209 </t:Code>
                        <t:Grade>4</t:Grade> 
                </t:Course>
               
	</t:Courses>

</t:Transcript>
