=== NetsanetGeb/XML-Processing-and-Parsing/src/xmlprocessing/xsd/CompanyInfoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.CompanyInfo.se" elementFormDefault="qualified">

	<xsd:element name="Companies">
		<xsd:complexType>
			<xsd:sequence>

				<xsd:element name="Company" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="Name" type="xsd:string" />

							<xsd:element name="CompanyNumber" type="xsd:integer" />

							<xsd:element name="PhoneNumber" type="xsd:integer" />

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== NetsanetGeb/XML-Processing-and-Parsing/xml/doc/CompanyInfoXMLDoc.xml
<?xml version="1.0" encoding="UTF-8"?>


<c:Companies
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:c='http://www.CompanyInfo.se'
    xsi:schemaLocation='http://www.CompanyInfo.se ../xsd/CompanyInfoSchema.xsd'>
        <c:Company>
		<c:Name> MIT </c:Name>
                <c:CompanyNumber>101010</c:CompanyNumber>
                <c:PhoneNumber>25194327834</c:PhoneNumber>
	</c:Company>
	<c:Company>
		<c:Name>MIT Mu</c:Name>
                <c:CompanyNumber>101010</c:CompanyNumber>
                <c:PhoneNumber>25194327834</c:PhoneNumber>
	</c:Company>
</c:Companies>
