=== NetsanetGeb/XML-Processing-and-Parsing/src/xmlprocessing/xsd/ShortCvSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ShortCv.se" elementFormDefault="qualified">

	<xsd:element name="CV">
		<xsd:complexType>
			<xsd:sequence>

				<xsd:element name="FirstName" type="xsd:string" />

				<xsd:element name="LastName" type="xsd:string" />

				<xsd:element name="PersonNumber">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="\d{6}-\d{4}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
                                
                                 <xsd:element name="Address" type="xsd:string"/>
                 

                               <xsd:element name="LanguageSkils" type="xsd:string"/> 

                               <xsd:element name="DrivingLicence" type="xsd:string"/>

                               <xsd:element name="JobApplication">
                                   <xsd:complexType>
                                       <xsd:sequence>
                                           <xsd:element name="Position" type="xsd:string"/>
                                           <xsd:element name="JobType" type="xsd:string"/>
                                       </xsd:sequence>
                                   </xsd:complexType>
                               </xsd:element>

                                <xsd:element name="References">
                                   <xsd:complexType>
                                       <xsd:sequence>
                                           <xsd:element name="RefereeName" type="xsd:string"/>
                                           <xsd:element name="RefereeEmail" type="xsd:string"/>
                                             
                                       </xsd:sequence>
                                   </xsd:complexType>
                               </xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== NetsanetGeb/XML-Processing-and-Parsing/xml/doc/ShortCvXMLDoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<cv:CV
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:cv='http://www.ShortCv.se'
    xsi:schemaLocation='http://www.ShortCv.se ../xsd/ShortCvSchema.xsd'>
    <cv:FirstName>Netsanet</cv:FirstName>
	<cv:LastName>Gebretsadkan</cv:LastName>
	<cv:PersonNumber>940823-0580</cv:PersonNumber>
        <cv:Address>Hanstavagen 49, Kista </cv:Address>
        <cv:LanguageSkils> Tigringa, Amharic, English</cv:LanguageSkils>
        <cv:DrivingLicence> D </cv:DrivingLicence>
        <cv:JobApplication>
            <cv:Position>Programmer</cv:Position>
            <cv:JobType> Part time</cv:JobType>
        </cv:JobApplication>
        <cv:References>
            <cv:RefereeName> Tedros Getu</cv:RefereeName>
            <cv:RefereeEmail> tedrosgt2@gmail.com </cv:RefereeEmail>
        </cv:References>

</cv:CV>
